# Generated by Django 3.0.3 on 2020-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='头像'),
        ),
    ]
