# Generated by Django 3.0.3 on 2020-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200307_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
